# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learn_git' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for learn_git

  target 'learn_gitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'learn_gitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
